spring:
  rabbitmq:
    host: 192.168.1.254
    port: 5672
    username: guest
    password: guest
  # 邮箱配置
#  mail:
#    host: smtp.qq.com
#    username: xxxxxxx@qq.com
#    password: xxxxxxxxxx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#  boot:
#    admin:
#      notify:
#        mail:
#          # 启用邮件通知
#          enabled: true
#          # 以逗号分隔的邮件收件人列表
#          to: xxxxxxx@xxxx.com
#          from: ${spring.mail.username}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS