spring:
  # rabbitmq 设置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 日志设置
logging:
  level:
    root: info
  path: D:/Object/spring-logs/userCenter
  file:
    max-history: 90

server:
  tomcat:
    accesslog:
      directory: D:/Object/spring-logs/userCenter
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS