version: "3"
services:
  #################### rabbitmq #####################
  rabbitmq:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${RABBITMQ_NAME}:${RABBITMQ_VERSION}
    hostname: spring-rabbitmq
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ${RABBITMQ_LIB_DATA}:/var/rabbitmq/lib
    restart: always
    network_mode: "bridge"

  ################ spring-cloud-eureka ##############
  server_eureka:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_EUREKA_NAME}:${SERVER_EUREKA_VERSION}
    hostname: spring-eureka
    ports:
    - "${SERVER_EUREKA_PORT}:9010"
    volumes:
    - ${SERVER_EUREKA_DATA}:/data/:rw
    - ${SERVER_EUREKA_LOGS}:/data/logs/:rw
    - ${SH_DIR}:/usr/local/sh/:rw
    tty: true
    restart: always
    network_mode: "bridge"

  ################ spring-cloud-eureka-1 ############
  server_eureka_1:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_EUREKA_1_NAME}:${SERVER_EUREKA_1_VERSION}
    hostname: spring-eureka-1
    ports:
    - "${SERVER_EUREKA_1_PORT}:9011"
    volumes:
    - ${SERVER_EUREKA_1_DATA}:/data/:rw
    - ${SERVER_EUREKA_1_LOGS}:/data/logs/:rw
    - ${SH_DIR}:/usr/local/sh/:rw
    tty: true
    restart: always
    network_mode: "bridge"

  ################ spring-cloud-config ##############
  server_config:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_CONFIG_NAME}:${SERVER_CONFIG_VERSION}
    hostname: spring-config
    ports:
    - "${SERVER_CONFIG_PORT}:9020"
    volumes:
    - ${SERVER_CONFIG_DATA}:/data/:rw
    - ${SERVER_CONFIG_LOGS}:/data/logs/:rw
    - ${SH_DIR}:/usr/local/sh/:rw
    tty: true
    restart: always
    network_mode: "bridge"

  ################ spring-cloud-zull ##############
  apigateway:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_APIGATEWAY_NAME}:${SERVER_APIGATEWAY_VERSION}
    hostname: spring-apigateway
    ports:
    - "${SERVER_APIGATEWAY_PORT}:9030"
    volumes:
    - ${SERVER_APIGATEWAY_DATA}:/data/:rw
    - ${SERVER_APIGATEWAY_LOGS}:/data/logs/:rw
    - ${SH_DIR}:/usr/local/sh/:rw
    tty: true
    restart: always
    network_mode: "bridge"

  ############# spring-cloud-zull-redis ############
  apigateway_redis:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_APIGATEWAY_REDIS_NAME}:${SERVER_APIGATEWAY_REDIS_VERSION}
    hostname: spring-apigateway-redis
    restart: always
    networks:
    - default
    ports:
    - "${SERVER_APIGATEWAY_REDIS_PORT}:6379"

  ######### spring-cloud-zull-phpredisadmin ########
  apigateway_phpredisadmin:
    image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${SERVER_APIGATEWAY_PHPREDISADMIN_NAME}:${SERVER_APIGATEWAY_PHPREDISADMIN_VERSION}
    ports:
    - "${SERVER_APIGATEWAY_PHPREDISADMIN_PORT}:80"
    restart: always
    networks:
    - default
    environment:
    - ADMIN_USER=${SERVER_APIGATEWAY_PHPREDISADMIN_USER}
    - ADMIN_PASS=${SERVER_APIGATEWAY_PHPREDISADMIN_PASS}
    - REDIS_1_HOST=apigateway_redis
    - REDIS_1_PORT=6379

networks:
  default: